### ISSUE TITLE
Few questions about nuget packages & repository

### ISSUE THREAD

**Issue by tomap** [TylerBrinks/Snap#37]
Hi,

I have a few questions about your repository:
* Why do you commit your packages? (folder packages) nuget restore works well, they could be skipped from the repository
Also, most of them are partially committed and thus prevent a 100% working restore.

* Why do you commit the packages you produced? .nupkg they are on nuget, you could skip them

* Is it your package on nuget here? https://www.nuget.org/packages/SNAP/
I suppose it is, but the description points to http://github.com/Acoustic/Snap. Could you fix?

* You seem to have a .Net 4.0 configuration and a .Net 4.5 configuration. I suppose you are using those configuration to compile 4.0 and 4.5 versions ? However, I don't understand how you change the target framework? manually between each compilation?

I'm asking all those questions to understand how you produce your builds, and if to fork or not for my needs.

Thank you

**Comment by TylerBrinks** [comment]
1. Never intended to commit packages - the project was put together prior to being on GitHub and as I recall the initial gitignore missed the package folder.
2. Same reason as #1.  I'm happy to take pull requests to clean up the process.
3. Next time I push to NuGet I'll update the description.  The link on the left side of the same page is correct.
4. Target frameworks are handled by NuGet when you install a package.  Right now there are 4.0 and 4.5 targets.  4.6 needs to be added - I'll do that next time I update the outdated references

Feel free to send a pull request at any time to update stuff.
